name: storybook

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      -
        name: Version
        id: Version
        run: |
          set -e
          export VERSION=$(jq '.version' < package.json | sed 's/"//g')
          echo "name=VERSION::$VERSION" >> $GITHUB_ENV
      -
        name: Install
        id: Install
        run: |
          npm install
      -
        name: Eslint
        id: Eslint
        run: |
          npm run lint
      -
        name: Test
        id: Test
        run: |
          npm test -- --coverage
      -
        name: Build and Publish
        id: Build
        run: |
          set -e
          echo $VERSION
          npm run build-storybook
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      -
        name: Prepare
        id: Prepare
        run: |
          DOCKER_IMAGE=ceruleandatahub/component-storybook
          TAGS="--tag ${DOCKER_IMAGE}:${VERSION} --tag ${DOCKER_IMAGE}:latest"
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=buildx_args::--build-arg VERSION=${VERSION} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            ${TAGS} --file Dockerfile .
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Docker Login
        if: success()
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Docker Build
        run: |
          docker buildx build --output "type=image,push=true" ${{ steps.prepare.outputs.buildx_args }}

